version: '3.7'

services:
  open-ca-core:
    image: fabric-openca-core
    container_name: fabric-openca-core
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - type: volume
        source: fabric-openca-core-volume
        target: /etc/hyperledger/fabric-ca-server
        consistency: delegated
    ports:
      - 7054:7054
    env_file:
      - ./.env
# # ./volumes/fabric-ca-server:/etc/hyperledger/fabric-ca-server:delegated

volumes:
  fabric-openca-core-volume:
    driver_opts:
      type: 'nfs'
      device: '${FABRIC_OPENCA_PATH}/volumes/fabric-ca-server'
      o: 'bind'
